import { env } from "@/lib/db";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const TAX_YEAR = "2027";

async function ensureSchema() {
  await env.DB.batch([
    env.DB.prepare("CREATE TABLE IF NOT EXISTS payroll_employees (id INTEGER PRIMARY KEY AUTOINCREMENT, employee_number TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, id_number TEXT, job_title TEXT NOT NULL, age_band TEXT NOT NULL DEFAULT 'UNDER_65', base_salary REAL NOT NULL DEFAULT 0, meat_benefit REAL NOT NULL DEFAULT 0, benefit_balance REAL NOT NULL DEFAULT 0, housing_deduction REAL NOT NULL DEFAULT 0, pension_deduction REAL NOT NULL DEFAULT 0, medical_deduction REAL NOT NULL DEFAULT 0, other_taxable_benefits REAL NOT NULL DEFAULT 0, other_deductions REAL NOT NULL DEFAULT 0, account_number TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS payroll_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, payroll_number TEXT NOT NULL UNIQUE, employee_id INTEGER NOT NULL, pay_period TEXT NOT NULL, base_salary REAL NOT NULL, meat_benefit REAL NOT NULL, opening_benefit_balance REAL NOT NULL, meat_purchases REAL NOT NULL, meat_excess_deduction REAL NOT NULL, closing_benefit_balance REAL NOT NULL, overtime_hours REAL NOT NULL, overtime_rate REAL NOT NULL, overtime_pay REAL NOT NULL, other_taxable_benefits REAL NOT NULL, gross_remuneration REAL NOT NULL, taxable_remuneration REAL NOT NULL, paye REAL NOT NULL, housing_deduction REAL NOT NULL, pension_deduction REAL NOT NULL, medical_deduction REAL NOT NULL, other_deductions REAL NOT NULL, total_deductions REAL NOT NULL, net_pay REAL NOT NULL, tax_year TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(employee_id) REFERENCES payroll_employees(id))"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS customer_accounts (id INTEGER PRIMARY KEY AUTOINCREMENT, account_number TEXT NOT NULL UNIQUE, name TEXT NOT NULL, credit_limit REAL NOT NULL DEFAULT 0, balance REAL NOT NULL DEFAULT 0, payment_terms_days INTEGER NOT NULL DEFAULT 30, status TEXT NOT NULL DEFAULT 'ACTIVE')"),
    env.DB.prepare("CREATE TABLE IF NOT EXISTS customer_purchases (id INTEGER PRIMARY KEY AUTOINCREMENT, account_id INTEGER NOT NULL, invoice_number TEXT NOT NULL UNIQUE, purchase_date TEXT NOT NULL, total REAL NOT NULL, balance REAL NOT NULL, status TEXT NOT NULL DEFAULT 'OPEN', FOREIGN KEY(account_id) REFERENCES customer_accounts(id))"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_payroll_runs_period_employee ON payroll_runs(pay_period,employee_id)"),
  ]);
  const now=new Date().toISOString();
  await env.DB.batch([
    env.DB.prepare("INSERT OR IGNORE INTO payroll_employees (employee_number,full_name,id_number,job_title,age_band,base_salary,meat_benefit,benefit_balance,housing_deduction,pension_deduction,medical_deduction,other_taxable_benefits,other_deductions,account_number,created_at) VALUES ('EMP-001','Naledi Mokoena','9001010000000','Butchery Manager','UNDER_65',18500,500,0,1800,0,0,0,0,'STAFF-001',?)").bind(now),
    env.DB.prepare("INSERT OR IGNORE INTO payroll_employees (employee_number,full_name,id_number,job_title,age_band,base_salary,meat_benefit,benefit_balance,housing_deduction,pension_deduction,medical_deduction,other_taxable_benefits,other_deductions,account_number,created_at) VALUES ('EMP-002','Johan Botha','8506140000000','Senior Butcher','UNDER_65',16200,500,0,1250,450,0,0,0,'STAFF-002',?)").bind(now),
    env.DB.prepare("INSERT OR IGNORE INTO payroll_employees (employee_number,full_name,id_number,job_title,age_band,base_salary,meat_benefit,benefit_balance,housing_deduction,pension_deduction,medical_deduction,other_taxable_benefits,other_deductions,account_number,created_at) VALUES ('EMP-003','Thandi Ndlovu','9302200000000','Cashier','UNDER_65',9800,500,0,0,0,0,0,0,'STAFF-003',?)").bind(now),
    env.DB.prepare("INSERT OR IGNORE INTO customer_accounts (account_number,name,credit_limit,balance,payment_terms_days,status) VALUES ('STAFF-001','Naledi Mokoena · Staff Account',5000,0,30,'ACTIVE')"),
    env.DB.prepare("INSERT OR IGNORE INTO customer_accounts (account_number,name,credit_limit,balance,payment_terms_days,status) VALUES ('STAFF-002','Johan Botha · Staff Account',5000,0,30,'ACTIVE')"),
    env.DB.prepare("INSERT OR IGNORE INTO customer_accounts (account_number,name,credit_limit,balance,payment_terms_days,status) VALUES ('STAFF-003','Thandi Ndlovu · Staff Account',5000,0,30,'ACTIVE')"),
  ]);
}

function annualTax(income:number) {
  if (income <= 245100) return income*.18;
  if (income <= 383100) return 44118+(income-245100)*.26;
  if (income <= 530200) return 79998+(income-383100)*.31;
  if (income <= 695800) return 125599+(income-530200)*.36;
  if (income <= 887000) return 185215+(income-695800)*.39;
  if (income <= 1878600) return 259783+(income-887000)*.41;
  return 666339+(income-1878600)*.45;
}

function monthlyPaye(monthlyTaxable:number, ageBand:string) {
  const rebates=17820+(ageBand==="AGE_65_74"||ageBand==="AGE_75_PLUS"?9765:0)+(ageBand==="AGE_75_PLUS"?3249:0);
  return Math.max(0,(annualTax(Math.max(0,monthlyTaxable)*12)-rebates)/12);
}

type Employee={id:number;employeeNumber:string;fullName:string;idNumber:string;jobTitle:string;ageBand:string;baseSalary:number;meatBenefit:number;benefitBalance:number;housingDeduction:number;pensionDeduction:number;medicalDeduction:number;otherTaxableBenefits:number;otherDeductions:number;accountNumber:string;active:number};
type PayrollRun={id:number;payrollNumber:string;employeeId:number;employeeName:string;employeeNumber:string;jobTitle:string;payPeriod:string;baseSalary:number;meatBenefit:number;openingBenefitBalance:number;meatPurchases:number;meatExcessDeduction:number;closingBenefitBalance:number;overtimeHours:number;overtimeRate:number;overtimePay:number;otherTaxableBenefits:number;grossRemuneration:number;taxableRemuneration:number;paye:number;housingDeduction:number;pensionDeduction:number;medicalDeduction:number;otherDeductions:number;totalDeductions:number;netPay:number;taxYear:string;createdAt:string};

async function generatePayslip(run:PayrollRun) {
  const pdf=await PDFDocument.create(); const page=pdf.addPage([595.28,841.89]); const regular=await pdf.embedFont(StandardFonts.Helvetica); const bold=await pdf.embedFont(StandardFonts.HelveticaBold); const red=rgb(.55,.08,.1); const dark=rgb(.12,.1,.1); const grey=rgb(.42,.39,.4);
  page.drawRectangle({x:0,y:758,width:595.28,height:84,color:dark}); page.drawRectangle({x:0,y:748,width:595.28,height:10,color:red});
  page.drawText("GEORGE'S BUTCHERY",{x:42,y:802,size:19,font:bold,color:rgb(1,1,1)}); page.drawText("EMPLOYEE PAYSLIP",{x:42,y:780,size:10,font:regular,color:rgb(.82,.75,.76)}); page.drawText(run.payrollNumber,{x:430,y:791,size:10,font:bold,color:rgb(1,1,1)});
  const label=(text:string,x:number,y:number)=>page.drawText(text.toUpperCase(),{x,y,size:7,font:bold,color:grey}); const value=(text:string,x:number,y:number,size=10)=>page.drawText(text,{x,y,size,font:bold,color:dark}); const money=(n:number)=>`R ${n.toLocaleString("en-ZA",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  label("Employee",42,710); value(run.employeeName,42,691,14); label("Employee number",320,710); value(run.employeeNumber,320,691); label("Position",42,663); value(run.jobTitle,42,644); label("Pay period",320,663); value(run.payPeriod,320,644); label("SARS tax year",455,663); value(run.taxYear,455,644);
  page.drawLine({start:{x:42,y:620},end:{x:553,y:620},thickness:1,color:rgb(.85,.82,.82)}); label("Earnings and benefits",42,594); label("Amount",475,594);
  const earnings=[["Base salary",run.baseSalary],[`Overtime (${run.overtimeHours.toFixed(2)} hrs @ ${money(run.overtimeRate)})`,run.overtimePay],["Meat account benefit",run.meatBenefit],["Other taxable benefits",run.otherTaxableBenefits]] as const; let y=568; for(const [name,amount] of earnings){page.drawText(name,{x:42,y,size:9,font:regular,color:dark});page.drawText(money(amount),{x:470,y,size:9,font:bold,color:dark});y-=25;}
  y-=18; page.drawRectangle({x:36,y:y-4,width:523,height:31,color:rgb(.96,.94,.94)}); page.drawText("GROSS REMUNERATION",{x:42,y:y+7,size:9,font:bold,color:dark}); page.drawText(money(run.grossRemuneration),{x:470,y:y+7,size:9,font:bold,color:red}); y-=58;
  label("Deductions",42,y); label("Amount",475,y); y-=26; const deductions=[["PAYE",run.paye],["Housing",run.housingDeduction],["Pension / provident",run.pensionDeduction],["Medical aid",run.medicalDeduction],["Meat purchases above benefit",run.meatExcessDeduction],["Other deductions",run.otherDeductions]] as const; for(const [name,amount] of deductions){page.drawText(name,{x:42,y,size:9,font:regular,color:dark});page.drawText(money(amount),{x:470,y,size:9,font:bold,color:dark});y-=23;}
  y-=30; page.drawRectangle({x:36,y:y-8,width:523,height:54,color:dark}); page.drawText("NET PAY",{x:52,y:y+10,size:12,font:bold,color:rgb(1,1,1)}); page.drawText(money(run.netPay),{x:420,y:y+8,size:16,font:bold,color:rgb(1,1,1)}); y-=52;
  label("Meat benefit account",42,y); y-=21; page.drawText(`Opening surplus ${money(run.openingBenefitBalance)}  +  monthly benefit ${money(run.meatBenefit)}  -  purchases ${money(run.meatPurchases)}  =  closing surplus ${money(run.closingBenefitBalance)}`,{x:42,y,size:8,font:regular,color:dark});
  page.drawText("PAYE calculated using SARS 2027 annual tax brackets and applicable age rebate. Payroll estimates must be reviewed before statutory submission.",{x:42,y:74,size:7,font:regular,color:grey,maxWidth:500}); page.drawText("George's Butchery  |  Confidential employee record",{x:42,y:43,size:7,font:bold,color:red});
  return pdf.save();
}

export async function GET(request:Request) {
  await ensureSchema(); const url=new URL(request.url); const payslipId=Number(url.searchParams.get("payslip")); const period=url.searchParams.get("period")||new Date().toISOString().slice(0,7); const periodStart=`${period}-01`; const following=new Date(`${periodStart}T12:00:00Z`); following.setUTCMonth(following.getUTCMonth()+1); const periodEnd=following.toISOString().slice(0,10);
  const runSelect="SELECT r.id,r.payroll_number AS payrollNumber,r.employee_id AS employeeId,e.full_name AS employeeName,e.employee_number AS employeeNumber,e.job_title AS jobTitle,r.pay_period AS payPeriod,r.base_salary AS baseSalary,r.meat_benefit AS meatBenefit,r.opening_benefit_balance AS openingBenefitBalance,r.meat_purchases AS meatPurchases,r.meat_excess_deduction AS meatExcessDeduction,r.closing_benefit_balance AS closingBenefitBalance,r.overtime_hours AS overtimeHours,r.overtime_rate AS overtimeRate,r.overtime_pay AS overtimePay,r.other_taxable_benefits AS otherTaxableBenefits,r.gross_remuneration AS grossRemuneration,r.taxable_remuneration AS taxableRemuneration,r.paye,r.housing_deduction AS housingDeduction,r.pension_deduction AS pensionDeduction,r.medical_deduction AS medicalDeduction,r.other_deductions AS otherDeductions,r.total_deductions AS totalDeductions,r.net_pay AS netPay,r.tax_year AS taxYear,r.created_at AS createdAt FROM payroll_runs r JOIN payroll_employees e ON e.id=r.employee_id";
  if(payslipId){const run=await env.DB.prepare(`${runSelect} WHERE r.id=?`).bind(payslipId).first<PayrollRun>();if(!run)return new Response("Payslip not found",{status:404});const bytes=await generatePayslip(run);const safe=run.employeeName.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"");return new Response(bytes as BodyInit,{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${safe}-${run.payPeriod}-Payslip.pdf"`}});}
  const [employees,runs,accountPurchases]=await Promise.all([
    env.DB.prepare("SELECT id,employee_number AS employeeNumber,full_name AS fullName,id_number AS idNumber,job_title AS jobTitle,age_band AS ageBand,base_salary AS baseSalary,meat_benefit AS meatBenefit,benefit_balance AS benefitBalance,housing_deduction AS housingDeduction,pension_deduction AS pensionDeduction,medical_deduction AS medicalDeduction,other_taxable_benefits AS otherTaxableBenefits,other_deductions AS otherDeductions,account_number AS accountNumber,active FROM payroll_employees WHERE active=1 ORDER BY full_name").all<Employee>(),
    env.DB.prepare(`${runSelect} ORDER BY r.id DESC LIMIT 100`).all<PayrollRun>(),
    env.DB.prepare("SELECT e.id AS employeeId,e.account_number AS accountNumber,COALESCE(SUM(p.total),0) AS total,COUNT(p.id) AS invoiceCount FROM payroll_employees e LEFT JOIN customer_accounts a ON a.account_number=e.account_number LEFT JOIN customer_purchases p ON p.account_id=a.id AND p.purchase_date>=? AND p.purchase_date<? WHERE e.active=1 GROUP BY e.id,e.account_number ORDER BY e.id").bind(periodStart,periodEnd).all<{employeeId:number;accountNumber:string;total:number;invoiceCount:number}>(),
  ]); return Response.json({employees:employees.results,runs:runs.results,accountPurchases:accountPurchases.results,period,taxYear:TAX_YEAR});
}

export async function POST(request:Request) {
  await ensureSchema(); const body=await request.json() as Record<string,unknown>; const now=new Date().toISOString();
  if(body.action==="employee"){
    const name=String(body.fullName??"").trim(); const number=String(body.employeeNumber??"").trim(); if(!name||!number)return Response.json({error:"Employee number and full name are required"},{status:400});
    await env.DB.prepare("INSERT INTO payroll_employees (employee_number,full_name,id_number,job_title,age_band,base_salary,meat_benefit,benefit_balance,housing_deduction,pension_deduction,medical_deduction,other_taxable_benefits,other_deductions,account_number,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(employee_number) DO UPDATE SET full_name=excluded.full_name,id_number=excluded.id_number,job_title=excluded.job_title,age_band=excluded.age_band,base_salary=excluded.base_salary,meat_benefit=excluded.meat_benefit,housing_deduction=excluded.housing_deduction,pension_deduction=excluded.pension_deduction,medical_deduction=excluded.medical_deduction,other_taxable_benefits=excluded.other_taxable_benefits,other_deductions=excluded.other_deductions,account_number=excluded.account_number").bind(number,name,String(body.idNumber??""),String(body.jobTitle??"Staff member"),String(body.ageBand??"UNDER_65"),Number(body.baseSalary)||0,Number(body.meatBenefit)||0,0,Number(body.housingDeduction)||0,Number(body.pensionDeduction)||0,Number(body.medicalDeduction)||0,Number(body.otherTaxableBenefits)||0,Number(body.otherDeductions)||0,String(body.accountNumber??""),now).run(); return Response.json({ok:true});
  }
  if(body.action==="run"){
    const employee=await env.DB.prepare("SELECT id,employee_number AS employeeNumber,full_name AS fullName,job_title AS jobTitle,age_band AS ageBand,base_salary AS baseSalary,meat_benefit AS meatBenefit,benefit_balance AS benefitBalance,housing_deduction AS housingDeduction,pension_deduction AS pensionDeduction,medical_deduction AS medicalDeduction,other_taxable_benefits AS otherTaxableBenefits,other_deductions AS otherDeductions,account_number AS accountNumber FROM payroll_employees WHERE id=? AND active=1").bind(Number(body.employeeId)).first<Employee>(); if(!employee)return Response.json({error:"Choose an active employee"},{status:400});
    const period=String(body.payPeriod??""); const periodStart=`${period}-01`; const following=new Date(`${periodStart}T12:00:00Z`); following.setUTCMonth(following.getUTCMonth()+1); const periodEnd=following.toISOString().slice(0,10); const accountTotal=employee.accountNumber?await env.DB.prepare("SELECT COALESCE(SUM(p.total),0) AS total FROM customer_purchases p JOIN customer_accounts a ON a.id=p.account_id WHERE a.account_number=? AND p.purchase_date>=? AND p.purchase_date<?").bind(employee.accountNumber,periodStart,periodEnd).first<{total:number}>():null; const meatPurchases=Math.max(0,Number(accountTotal?.total)||0); const payrollNumber=`PAY-${period.replace("-","")}-${employee.employeeNumber}`; const previous=await env.DB.prepare("SELECT opening_benefit_balance AS openingBenefitBalance,meat_purchases AS meatPurchases FROM payroll_runs WHERE payroll_number=?").bind(payrollNumber).first<{openingBenefitBalance:number;meatPurchases:number}>(); const openingBenefit=previous?.openingBenefitBalance??employee.benefitBalance; const overtimeHours=Math.max(0,Number(body.overtimeHours)||0); const overtimeMultiplier=Math.max(1,Number(body.overtimeMultiplier)||1.5); const overtimeRate=employee.baseSalary/195*overtimeMultiplier; const overtimePay=overtimeHours*overtimeRate; const availableBenefit=openingBenefit+employee.meatBenefit; const meatExcess=Math.max(0,meatPurchases-availableBenefit); const closingBenefit=Math.max(0,availableBenefit-meatPurchases); const gross=employee.baseSalary+overtimePay+employee.meatBenefit+employee.otherTaxableBenefits; const taxable=gross; const paye=monthlyPaye(taxable,employee.ageBand); const totalDeductions=paye+employee.housingDeduction+employee.pensionDeduction+employee.medicalDeduction+employee.otherDeductions+meatExcess; const net=Math.max(0,employee.baseSalary+overtimePay-totalDeductions);
    const insert=await env.DB.prepare("INSERT INTO payroll_runs (payroll_number,employee_id,pay_period,base_salary,meat_benefit,opening_benefit_balance,meat_purchases,meat_excess_deduction,closing_benefit_balance,overtime_hours,overtime_rate,overtime_pay,other_taxable_benefits,gross_remuneration,taxable_remuneration,paye,housing_deduction,pension_deduction,medical_deduction,other_deductions,total_deductions,net_pay,tax_year,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(payroll_number) DO UPDATE SET meat_purchases=excluded.meat_purchases,meat_excess_deduction=excluded.meat_excess_deduction,closing_benefit_balance=excluded.closing_benefit_balance,overtime_hours=excluded.overtime_hours,overtime_rate=excluded.overtime_rate,overtime_pay=excluded.overtime_pay,gross_remuneration=excluded.gross_remuneration,taxable_remuneration=excluded.taxable_remuneration,paye=excluded.paye,total_deductions=excluded.total_deductions,net_pay=excluded.net_pay,created_at=excluded.created_at").bind(payrollNumber,employee.id,period,employee.baseSalary,employee.meatBenefit,openingBenefit,meatPurchases,meatExcess,closingBenefit,overtimeHours,overtimeRate,overtimePay,employee.otherTaxableBenefits,gross,taxable,paye,employee.housingDeduction,employee.pensionDeduction,employee.medicalDeduction,employee.otherDeductions,totalDeductions,net,TAX_YEAR,now).run();
    const settlementDelta=meatPurchases-(previous?.meatPurchases??0); const statements=[env.DB.prepare("UPDATE payroll_employees SET benefit_balance=? WHERE id=?").bind(closingBenefit,employee.id)]; if(employee.accountNumber&&settlementDelta!==0)statements.push(env.DB.prepare("UPDATE customer_accounts SET balance=MAX(0,balance-?) WHERE account_number=?").bind(settlementDelta,employee.accountNumber)); await env.DB.batch(statements); const row=await env.DB.prepare("SELECT id FROM payroll_runs WHERE payroll_number=?").bind(payrollNumber).first<{id:number}>(); return Response.json({ok:true,id:Number(insert.meta.last_row_id)||row?.id,payrollNumber,netPay:net,meatPurchases});
  }
  return Response.json({error:"Unknown payroll action"},{status:400});
}
